### ISSUE TITLE
'Add' element back to Endevor

### ISSUE THREAD

**Issue by zimlu02** [eclipse/che-che4z-explorer-for-endevor#14]
**Description:**
As Michelle, I want to be able to safely add an element back to Endevor, so that my local changes can be uploaded to Endevor repository. If the element is existing or there are any problems, I would like to receive an error message so I could check and correct it.

**The process for adding an element will be as follows:**
1. Click the Add file Icon (Talk to UX) to trigger add element.
2. Choose/Select the element that I want to add in Endevor
3. Once I click okay, target location will be prompted > CCID > Comment (Similar to edit)
4. Add element API is triggered and the tree is updated with the new element
5. If there are duplicates/problems, a warning message will appear to allow me to check on those errors.  

**Note:** This feature will only add one element at a time. Adding of multiple elements is out of scope.

**Tasks:**

- [ ] Modify the existing Add Element API
- [ ] Add Element is added as a command
- [ ] VSCode API to get the files from the file system is added
- [ ] Refresh the tree after adding the element

**Comment by nickImbirev** [comment]
resolved within #181 PR
