### ISSUE TITLE
Sign-in/Sign-out Support

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-explorer-for-endevor#161]
As Michelle, I want to be able to have the capability to sign-in and sign-out my elements. 

The following features will be provided:
1. An automatic sign-out when a user retrieves their elements
2. An error message that will allow the user to over-write the sign-out if an element is already sign-out
3. A capability to manually sign-in/sign-out an element

**Sample Use Cases:**

_Retrieve an Element_
1. Michelle wants to retrieve her element
2. E4E will have a parameter  in their settings like Automatic SIGN-OUT: Yes/No
3. If the element is not sign-out yet, then the element will be sign-out to Michelle once she clicks retrieve
4. If the element is sign-out to another user then an error message will appear asking if she wants to overwrite the sign-out

_Edit an Element_

1. Michelle wants to edit her element
2. E4E will have a parameter  in their settings like Automatic SIGN-OUT: Yes/No
3. If the element is not sign-out yet, then the element will be sign-out to Michelle once she saves the edited element
4. If the element is sign-out to another user then an error message will appear asking if she wants to overwrite the sign-out

_Manual Sign-in/Sign-out_

1. If Michelle wants to sign-in an element then she right-click > Sign-in Element. 
2. If Michelle wants to manually sign-out an element then she right-click > Sign-out Element

**Tasks:**
API Wrap:

- [ ] Modify existing retrieve function
- [ ] Sign-in Element
- [ ] Sign-out Element
- [ ] Overwrite Sign-out 

UI Changes

- [ ] Modify the retrieve to use the sign-out from the API
- [ ] Modify the edit to use the sign-out from the API
- [ ] Modify the retrieve with dependencies  to use the sign-out from the API
- [ ] New command to be added in the context menu

Other Changes

- [ ] Add the automatic sign-out in package.json

**Comment by nickImbirev** [comment]
resolved within #181 PR
