### ISSUE TITLE
Prioritized Issues and and High Impact Issues

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-explorer-for-endevor#162]
This Epic will handle the following issues:

- [x] https://github.com/eclipse/che-che4z-explorer-for-endevor/issues/115
- [x] https://github.com/eclipse/che-che4z-explorer-for-endevor/issues/139
- [x] https://github.com/eclipse/che-che4z-explorer-for-endevor/issues/128

**Comment by nickImbirev** [comment]
resolved within #181 PR
