### ISSUE TITLE
CI/CD and Test Improvements

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-explorer-for-endevor#163]
As an E4E developer,  I would like to do the following:

**Improve our CI/CD Process**

_Tasks:_

- [x] Automate the publishing of our VSIX file in VSC marketplace and Open VSX

**Improve our end to end testing process and convert our manual test to automated tests.** 

_Tasks:_

- [ ] Identify missing tests
- [ ] Convert our manual test to automated tests. Our goal is to increase our automated test to 30%
